import os
import gzip
import utils
import numpy
import argparse
import time
from param_formatter import ParamFormatter
from exception import InvalidValueException

def condense(infile, outfile):
    """
    infile must be a .gz file generated by the sql_to_json_parser.py
    condense will do the following:
        - replace trace data by averages
        - replace strings like '2.35 mi' to 2.35
    """
    t1 = time.time()
    fo = gzip.open(outfile, "w")
    fi = gzip.open(infile)
    param_formatter = ParamFormatter()
    n = 0
    n_values_ignored = 0
    for line in fi:
        d = {}
        w = utils.json_to_dict(line.strip())
        for k, v in w.items():
            if (isinstance(v, list)):
                # replace trace data by averages
                v = numpy.mean(utils.remove_null_values_single(v))
                d[k] = v
            else:
                # convert and replace units - for example, convert '2.35 mi' to 2.35
                try:
                    v = param_formatter.to_number(k, v)
                except InvalidValueException:
                    n_values_ignored += 1
                    pass        # if invalid, ignore so as not to include it in the output
        w_str = utils.dict_to_json(d)
        fo.write(w_str + "\n")
        n += 1
        if (n % 10000 == 0):
            print "Written %d workouts.." % (n)
    fi.close()
    fo.close()
    t2 = time.time()
    print "Time taken = " + str(t2 - t1) + " seconds"
    print "%d values ignored since they were invalid.." % (n_values_ignored)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Reads .gz file written by sql_to_json_parser.py and condenses all traces to average values, performs unit conversions etc.')
    parser.add_argument('--infile', type=str, help='.gz file', dest='infile')
    parser.add_argument('--outfile', type=str, help='.gz file', dest='outfile')
    args = parser.parse_args()
    if (args.infile is None or args.outfile is None):
        parser.print_usage()
    else:
        condense(args.infile,args.outfile)

