all:
	g++ -Wall -std=c++11 -O2 predictor_duration_evolving_user_cpp.cpp -llbfgs -o predictor_duration_evolving_user_cpp
	#g++ -Wall lbfgs_example.c -llbfgs -o lbfgs_example
clean:
	rm -f predictor_duration_evolving_user_cpp
